name: Java CI Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  java-ci:
    uses: techishthoughts-org/java-workflows/.github/workflows/java-ci-universal.yml@v2.0.3
    with:
      java-version: '21'
      build-tool: 'maven'
      maven-opts: '-Xmx4g'
      test-pattern: '**/*Test.java'
      os-matrix: 'ubuntu-latest,windows-latest'
      coverage-tool: 'jacoco'
