name: Java CI Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
jobs:
  java-ci:
    uses: techishthoughts-org/java-workflows/.github/workflows/java-ci-secure.yml@main
    with:
      java-version: '21'
      maven-args: '-B verify'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}